//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAdmin.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.BrookeAndCoWebServiceSoap")]
    public interface BrookeAndCoWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newStockOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void newStockOut(int stock_id, int transaction_id, string type, int quant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newStockOut", ReplyAction="*")]
        System.Threading.Tasks.Task newStockOutAsync(int stock_id, int transaction_id, string type, int quant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSalesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getSalesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSalesList", ReplyAction="*")]
        System.Threading.Tasks.Task getSalesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductByPcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getProductByPcode(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductByPcode", ReplyAction="*")]
        System.Threading.Tasks.Task getProductByPcodeAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyProductByPcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void modifyProductByPcode(string pcode, int quant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyProductByPcode", ReplyAction="*")]
        System.Threading.Tasks.Task modifyProductByPcodeAsync(string pcode, int quant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTopTen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getTopTen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTopTen", ReplyAction="*")]
        System.Threading.Tasks.Task getTopTenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProducts", ReplyAction="*")]
        System.Threading.Tasks.Task getProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBooks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBooks", ReplyAction="*")]
        System.Threading.Tasks.Task getBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBooksByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getBooksByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBooksByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task getBooksByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getBook(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBook", ReplyAction="*")]
        System.Threading.Tasks.Task getBookAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteBook(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteBook", ReplyAction="*")]
        System.Threading.Tasks.Task deleteBookAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createBook(int id, string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, int bookid, string authors, string pubCo, string pubDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createBook", ReplyAction="*")]
        System.Threading.Tasks.Task createBookAsync(int id, string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, int bookid, string authors, string pubCo, string pubDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateBook(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string authors, string pubCo, string pubDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBook", ReplyAction="*")]
        System.Threading.Tasks.Task updateBookAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string authors, string pubCo, string pubDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGames", ReplyAction="*")]
        System.Threading.Tasks.Task getGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGamesByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getGamesByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGamesByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task getGamesByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getGame(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGame", ReplyAction="*")]
        System.Threading.Tasks.Task getGameAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteGame(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteGame", ReplyAction="*")]
        System.Threading.Tasks.Task deleteGameAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createGame(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createGame", ReplyAction="*")]
        System.Threading.Tasks.Task createGameAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateGame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateGame(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateGame", ReplyAction="*")]
        System.Threading.Tasks.Task updateGameAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMovies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMovies", ReplyAction="*")]
        System.Threading.Tasks.Task getMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMoviesByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getMoviesByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMoviesByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task getMoviesByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMovie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getMovie(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMovie", ReplyAction="*")]
        System.Threading.Tasks.Task getMovieAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteMovie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteMovie(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteMovie", ReplyAction="*")]
        System.Threading.Tasks.Task deleteMovieAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createMovie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createMovie(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createMovie", ReplyAction="*")]
        System.Threading.Tasks.Task createMovieAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateMovie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateMovie(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateMovie", ReplyAction="*")]
        System.Threading.Tasks.Task updateMovieAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClients", ReplyAction="*")]
        System.Threading.Tasks.Task getClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveriesByOrderId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getDeliveriesByOrderId(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveriesByOrderId", ReplyAction="*")]
        System.Threading.Tasks.Task getDeliveriesByOrderIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createShipment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createShipment(int order_id, int address_id, int service_id, string delivery_date, double total_cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createShipment", ReplyAction="*")]
        System.Threading.Tasks.Task createShipmentAsync(int order_id, int address_id, int service_id, string delivery_date, double total_cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateClientExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void validateClientExists(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateClientExists", ReplyAction="*")]
        System.Threading.Tasks.Task validateClientExistsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClient", ReplyAction="*")]
        System.Threading.Tasks.Task getClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getClientByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task getClientByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserNameIsFree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CheckUserNameIsFree(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserNameIsFree", ReplyAction="*")]
        System.Threading.Tasks.Task CheckUserNameIsFreeAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createClient(string email, string username, string password, string name, string lastname, string bday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createClient", ReplyAction="*")]
        System.Threading.Tasks.Task createClientAsync(string email, string username, string password, string name, string lastname, string bday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void modifyClient(int id, string email, string username, string password, string name, string lastname, string bday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyClient", ReplyAction="*")]
        System.Threading.Tasks.Task modifyClientAsync(int id, string email, string username, string password, string name, string lastname, string bday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteClient", ReplyAction="*")]
        System.Threading.Tasks.Task deleteClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrders", ReplyAction="*")]
        System.Threading.Tasks.Task getOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAllEntriesFromOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteAllEntriesFromOrder(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAllEntriesFromOrder", ReplyAction="*")]
        System.Threading.Tasks.Task deleteAllEntriesFromOrderAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrdersByClientId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getOrdersByClientId(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrdersByClientId", ReplyAction="*")]
        System.Threading.Tasks.Task getOrdersByClientIdAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createNewOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createNewOrder(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createNewOrder", ReplyAction="*")]
        System.Threading.Tasks.Task createNewOrderAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyOrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void modifyOrderStatus(int orderId, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task modifyOrderStatusAsync(int orderId, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEntries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEntries", ReplyAction="*")]
        System.Threading.Tasks.Task getEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addEntryToOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void addEntryToOrder(int orderId, string pcode, int quantity, double price, int basket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addEntryToOrder", ReplyAction="*")]
        System.Threading.Tasks.Task addEntryToOrderAsync(int orderId, string pcode, int quantity, double price, int basket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteEntryFromOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteEntryFromOrder(int orderId, string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteEntryFromOrder", ReplyAction="*")]
        System.Threading.Tasks.Task deleteEntryFromOrderAsync(int orderId, string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteEntry(int orderId, string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteEntry", ReplyAction="*")]
        System.Threading.Tasks.Task deleteEntryAsync(int orderId, string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEntriesByOrderId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getEntriesByOrderId(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEntriesByOrderId", ReplyAction="*")]
        System.Threading.Tasks.Task getEntriesByOrderIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryAdress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getDeliveryAdress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryAdress", ReplyAction="*")]
        System.Threading.Tasks.Task getDeliveryAdressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryAdressesByClientId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getDeliveryAdressesByClientId(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryAdressesByClientId", ReplyAction="*")]
        System.Threading.Tasks.Task getDeliveryAdressesByClientIdAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryAdressById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getDeliveryAdressById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDeliveryAdressById", ReplyAction="*")]
        System.Threading.Tasks.Task getDeliveryAdressByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCardsByClientId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getCardsByClientId(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCardsByClientId", ReplyAction="*")]
        System.Threading.Tasks.Task getCardsByClientIdAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCardById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getCardById(int card_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCardById", ReplyAction="*")]
        System.Threading.Tasks.Task getCardByIdAsync(int card_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyClientCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void modifyClientCard(int id, string holdername, string expiration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyClientCard", ReplyAction="*")]
        System.Threading.Tasks.Task modifyClientCardAsync(int id, string holdername, string expiration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteClientCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteClientCard(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteClientCard", ReplyAction="*")]
        System.Threading.Tasks.Task deleteClientCardAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createClientCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createClientCard(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createClientCard", ReplyAction="*")]
        System.Threading.Tasks.Task createClientCardAsync(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createTemporaryClientCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createTemporaryClientCard(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration, string delete_on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createTemporaryClientCard", ReplyAction="*")]
        System.Threading.Tasks.Task createTemporaryClientCardAsync(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration, string delete_on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void modifyDeliveryAddress(int id, string country, string province, string city, string street, int civicnumber, string appartment, string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task modifyDeliveryAddressAsync(int id, string country, string province, string city, string street, int civicnumber, string appartment, string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createDeliveryAddress(string country, string province, string city, string street, int civicnumber, string appartment, string zipcode, int client_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task createDeliveryAddressAsync(string country, string province, string city, string street, int civicnumber, string appartment, string zipcode, int client_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteDeliveryAddress(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task deleteDeliveryAddressAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServicesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getServicesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServicesList", ReplyAction="*")]
        System.Threading.Tasks.Task getServicesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServiceById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getServiceById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServiceById", ReplyAction="*")]
        System.Threading.Tasks.Task getServiceByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientTransactionById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getClientTransactionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientTransactionById", ReplyAction="*")]
        System.Threading.Tasks.Task getClientTransactionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createClientTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void createClientTransaction(int id, int card_id, string transaction_confirmation, string status, string validation, double amount, int order_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createClientTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task createClientTransactionAsync(int id, int card_id, string transaction_confirmation, string status, string validation, double amount, int order_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStockIns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getStockIns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStockIns", ReplyAction="*")]
        System.Threading.Tasks.Task getStockInsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStockInListByPcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getStockInListByPcode(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStockInListByPcode", ReplyAction="*")]
        System.Threading.Tasks.Task getStockInListByPcodeAsync(string pcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStockOuts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getStockOuts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStockOuts", ReplyAction="*")]
        System.Threading.Tasks.Task getStockOutsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BrookeAndCoWebServiceSoapChannel : ConsoleAdmin.ServiceRef.BrookeAndCoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrookeAndCoWebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleAdmin.ServiceRef.BrookeAndCoWebServiceSoap>, ConsoleAdmin.ServiceRef.BrookeAndCoWebServiceSoap {
        
        public BrookeAndCoWebServiceSoapClient() {
        }
        
        public BrookeAndCoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrookeAndCoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrookeAndCoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrookeAndCoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void newStockOut(int stock_id, int transaction_id, string type, int quant) {
            base.Channel.newStockOut(stock_id, transaction_id, type, quant);
        }
        
        public System.Threading.Tasks.Task newStockOutAsync(int stock_id, int transaction_id, string type, int quant) {
            return base.Channel.newStockOutAsync(stock_id, transaction_id, type, quant);
        }
        
        public void getSalesList() {
            base.Channel.getSalesList();
        }
        
        public System.Threading.Tasks.Task getSalesListAsync() {
            return base.Channel.getSalesListAsync();
        }
        
        public void getProductByPcode(string pcode) {
            base.Channel.getProductByPcode(pcode);
        }
        
        public System.Threading.Tasks.Task getProductByPcodeAsync(string pcode) {
            return base.Channel.getProductByPcodeAsync(pcode);
        }
        
        public void modifyProductByPcode(string pcode, int quant) {
            base.Channel.modifyProductByPcode(pcode, quant);
        }
        
        public System.Threading.Tasks.Task modifyProductByPcodeAsync(string pcode, int quant) {
            return base.Channel.modifyProductByPcodeAsync(pcode, quant);
        }
        
        public void getTopTen() {
            base.Channel.getTopTen();
        }
        
        public System.Threading.Tasks.Task getTopTenAsync() {
            return base.Channel.getTopTenAsync();
        }
        
        public void getProducts() {
            base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
        
        public void getBooks() {
            base.Channel.getBooks();
        }
        
        public System.Threading.Tasks.Task getBooksAsync() {
            return base.Channel.getBooksAsync();
        }
        
        public void getBooksByCategory(string category) {
            base.Channel.getBooksByCategory(category);
        }
        
        public System.Threading.Tasks.Task getBooksByCategoryAsync(string category) {
            return base.Channel.getBooksByCategoryAsync(category);
        }
        
        public void getBook(string pcode) {
            base.Channel.getBook(pcode);
        }
        
        public System.Threading.Tasks.Task getBookAsync(string pcode) {
            return base.Channel.getBookAsync(pcode);
        }
        
        public void deleteBook(string pcode) {
            base.Channel.deleteBook(pcode);
        }
        
        public System.Threading.Tasks.Task deleteBookAsync(string pcode) {
            return base.Channel.deleteBookAsync(pcode);
        }
        
        public void createBook(int id, string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, int bookid, string authors, string pubCo, string pubDate) {
            base.Channel.createBook(id, pcode, picture, type, title, category, inventory, genre, price, bookid, authors, pubCo, pubDate);
        }
        
        public System.Threading.Tasks.Task createBookAsync(int id, string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, int bookid, string authors, string pubCo, string pubDate) {
            return base.Channel.createBookAsync(id, pcode, picture, type, title, category, inventory, genre, price, bookid, authors, pubCo, pubDate);
        }
        
        public void updateBook(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string authors, string pubCo, string pubDate) {
            base.Channel.updateBook(pcode, picture, type, title, category, inventory, genre, price, authors, pubCo, pubDate);
        }
        
        public System.Threading.Tasks.Task updateBookAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string authors, string pubCo, string pubDate) {
            return base.Channel.updateBookAsync(pcode, picture, type, title, category, inventory, genre, price, authors, pubCo, pubDate);
        }
        
        public void getGames() {
            base.Channel.getGames();
        }
        
        public System.Threading.Tasks.Task getGamesAsync() {
            return base.Channel.getGamesAsync();
        }
        
        public void getGamesByCategory(string category) {
            base.Channel.getGamesByCategory(category);
        }
        
        public System.Threading.Tasks.Task getGamesByCategoryAsync(string category) {
            return base.Channel.getGamesByCategoryAsync(category);
        }
        
        public void getGame(string pcode) {
            base.Channel.getGame(pcode);
        }
        
        public System.Threading.Tasks.Task getGameAsync(string pcode) {
            return base.Channel.getGameAsync(pcode);
        }
        
        public void deleteGame(string pcode) {
            base.Channel.deleteGame(pcode);
        }
        
        public System.Threading.Tasks.Task deleteGameAsync(string pcode) {
            return base.Channel.deleteGameAsync(pcode);
        }
        
        public void createGame(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate) {
            base.Channel.createGame(pcode, picture, type, title, category, inventory, genre, price, console, company, reldate);
        }
        
        public System.Threading.Tasks.Task createGameAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate) {
            return base.Channel.createGameAsync(pcode, picture, type, title, category, inventory, genre, price, console, company, reldate);
        }
        
        public void updateGame(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate) {
            base.Channel.updateGame(pcode, picture, type, title, category, inventory, genre, price, console, company, reldate);
        }
        
        public System.Threading.Tasks.Task updateGameAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string console, string company, string reldate) {
            return base.Channel.updateGameAsync(pcode, picture, type, title, category, inventory, genre, price, console, company, reldate);
        }
        
        public void getMovies() {
            base.Channel.getMovies();
        }
        
        public System.Threading.Tasks.Task getMoviesAsync() {
            return base.Channel.getMoviesAsync();
        }
        
        public void getMoviesByCategory(string category) {
            base.Channel.getMoviesByCategory(category);
        }
        
        public System.Threading.Tasks.Task getMoviesByCategoryAsync(string category) {
            return base.Channel.getMoviesByCategoryAsync(category);
        }
        
        public void getMovie(string pcode) {
            base.Channel.getMovie(pcode);
        }
        
        public System.Threading.Tasks.Task getMovieAsync(string pcode) {
            return base.Channel.getMovieAsync(pcode);
        }
        
        public void deleteMovie(string pcode) {
            base.Channel.deleteMovie(pcode);
        }
        
        public System.Threading.Tasks.Task deleteMovieAsync(string pcode) {
            return base.Channel.deleteMovieAsync(pcode);
        }
        
        public void createMovie(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear) {
            base.Channel.createMovie(pcode, picture, type, title, category, inventory, genre, price, director, actors, relyear);
        }
        
        public System.Threading.Tasks.Task createMovieAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear) {
            return base.Channel.createMovieAsync(pcode, picture, type, title, category, inventory, genre, price, director, actors, relyear);
        }
        
        public void updateMovie(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear) {
            base.Channel.updateMovie(pcode, picture, type, title, category, inventory, genre, price, director, actors, relyear);
        }
        
        public System.Threading.Tasks.Task updateMovieAsync(string pcode, string picture, string type, string title, string category, int inventory, string genre, double price, string director, string actors, string relyear) {
            return base.Channel.updateMovieAsync(pcode, picture, type, title, category, inventory, genre, price, director, actors, relyear);
        }
        
        public void getClients() {
            base.Channel.getClients();
        }
        
        public System.Threading.Tasks.Task getClientsAsync() {
            return base.Channel.getClientsAsync();
        }
        
        public void getDeliveriesByOrderId(int orderId) {
            base.Channel.getDeliveriesByOrderId(orderId);
        }
        
        public System.Threading.Tasks.Task getDeliveriesByOrderIdAsync(int orderId) {
            return base.Channel.getDeliveriesByOrderIdAsync(orderId);
        }
        
        public void createShipment(int order_id, int address_id, int service_id, string delivery_date, double total_cost) {
            base.Channel.createShipment(order_id, address_id, service_id, delivery_date, total_cost);
        }
        
        public System.Threading.Tasks.Task createShipmentAsync(int order_id, int address_id, int service_id, string delivery_date, double total_cost) {
            return base.Channel.createShipmentAsync(order_id, address_id, service_id, delivery_date, total_cost);
        }
        
        public void validateClientExists(string username, string password) {
            base.Channel.validateClientExists(username, password);
        }
        
        public System.Threading.Tasks.Task validateClientExistsAsync(string username, string password) {
            return base.Channel.validateClientExistsAsync(username, password);
        }
        
        public void getClient(int id) {
            base.Channel.getClient(id);
        }
        
        public System.Threading.Tasks.Task getClientAsync(int id) {
            return base.Channel.getClientAsync(id);
        }
        
        public void getClientByEmail(string email) {
            base.Channel.getClientByEmail(email);
        }
        
        public System.Threading.Tasks.Task getClientByEmailAsync(string email) {
            return base.Channel.getClientByEmailAsync(email);
        }
        
        public void CheckUserNameIsFree(string username) {
            base.Channel.CheckUserNameIsFree(username);
        }
        
        public System.Threading.Tasks.Task CheckUserNameIsFreeAsync(string username) {
            return base.Channel.CheckUserNameIsFreeAsync(username);
        }
        
        public void createClient(string email, string username, string password, string name, string lastname, string bday) {
            base.Channel.createClient(email, username, password, name, lastname, bday);
        }
        
        public System.Threading.Tasks.Task createClientAsync(string email, string username, string password, string name, string lastname, string bday) {
            return base.Channel.createClientAsync(email, username, password, name, lastname, bday);
        }
        
        public void modifyClient(int id, string email, string username, string password, string name, string lastname, string bday) {
            base.Channel.modifyClient(id, email, username, password, name, lastname, bday);
        }
        
        public System.Threading.Tasks.Task modifyClientAsync(int id, string email, string username, string password, string name, string lastname, string bday) {
            return base.Channel.modifyClientAsync(id, email, username, password, name, lastname, bday);
        }
        
        public void deleteClient(int id) {
            base.Channel.deleteClient(id);
        }
        
        public System.Threading.Tasks.Task deleteClientAsync(int id) {
            return base.Channel.deleteClientAsync(id);
        }
        
        public void getOrders() {
            base.Channel.getOrders();
        }
        
        public System.Threading.Tasks.Task getOrdersAsync() {
            return base.Channel.getOrdersAsync();
        }
        
        public void deleteAllEntriesFromOrder(int orderId) {
            base.Channel.deleteAllEntriesFromOrder(orderId);
        }
        
        public System.Threading.Tasks.Task deleteAllEntriesFromOrderAsync(int orderId) {
            return base.Channel.deleteAllEntriesFromOrderAsync(orderId);
        }
        
        public void getOrdersByClientId(int clientId) {
            base.Channel.getOrdersByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task getOrdersByClientIdAsync(int clientId) {
            return base.Channel.getOrdersByClientIdAsync(clientId);
        }
        
        public void createNewOrder(int clientId) {
            base.Channel.createNewOrder(clientId);
        }
        
        public System.Threading.Tasks.Task createNewOrderAsync(int clientId) {
            return base.Channel.createNewOrderAsync(clientId);
        }
        
        public void modifyOrderStatus(int orderId, string date) {
            base.Channel.modifyOrderStatus(orderId, date);
        }
        
        public System.Threading.Tasks.Task modifyOrderStatusAsync(int orderId, string date) {
            return base.Channel.modifyOrderStatusAsync(orderId, date);
        }
        
        public void getEntries() {
            base.Channel.getEntries();
        }
        
        public System.Threading.Tasks.Task getEntriesAsync() {
            return base.Channel.getEntriesAsync();
        }
        
        public void addEntryToOrder(int orderId, string pcode, int quantity, double price, int basket) {
            base.Channel.addEntryToOrder(orderId, pcode, quantity, price, basket);
        }
        
        public System.Threading.Tasks.Task addEntryToOrderAsync(int orderId, string pcode, int quantity, double price, int basket) {
            return base.Channel.addEntryToOrderAsync(orderId, pcode, quantity, price, basket);
        }
        
        public void deleteEntryFromOrder(int orderId, string pcode) {
            base.Channel.deleteEntryFromOrder(orderId, pcode);
        }
        
        public System.Threading.Tasks.Task deleteEntryFromOrderAsync(int orderId, string pcode) {
            return base.Channel.deleteEntryFromOrderAsync(orderId, pcode);
        }
        
        public void deleteEntry(int orderId, string pcode) {
            base.Channel.deleteEntry(orderId, pcode);
        }
        
        public System.Threading.Tasks.Task deleteEntryAsync(int orderId, string pcode) {
            return base.Channel.deleteEntryAsync(orderId, pcode);
        }
        
        public void getEntriesByOrderId(int orderId) {
            base.Channel.getEntriesByOrderId(orderId);
        }
        
        public System.Threading.Tasks.Task getEntriesByOrderIdAsync(int orderId) {
            return base.Channel.getEntriesByOrderIdAsync(orderId);
        }
        
        public void getDeliveryAdress() {
            base.Channel.getDeliveryAdress();
        }
        
        public System.Threading.Tasks.Task getDeliveryAdressAsync() {
            return base.Channel.getDeliveryAdressAsync();
        }
        
        public void getDeliveryAdressesByClientId(int clientId) {
            base.Channel.getDeliveryAdressesByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task getDeliveryAdressesByClientIdAsync(int clientId) {
            return base.Channel.getDeliveryAdressesByClientIdAsync(clientId);
        }
        
        public void getDeliveryAdressById(int id) {
            base.Channel.getDeliveryAdressById(id);
        }
        
        public System.Threading.Tasks.Task getDeliveryAdressByIdAsync(int id) {
            return base.Channel.getDeliveryAdressByIdAsync(id);
        }
        
        public void getCardsByClientId(int clientId) {
            base.Channel.getCardsByClientId(clientId);
        }
        
        public System.Threading.Tasks.Task getCardsByClientIdAsync(int clientId) {
            return base.Channel.getCardsByClientIdAsync(clientId);
        }
        
        public void getCardById(int card_id) {
            base.Channel.getCardById(card_id);
        }
        
        public System.Threading.Tasks.Task getCardByIdAsync(int card_id) {
            return base.Channel.getCardByIdAsync(card_id);
        }
        
        public void modifyClientCard(int id, string holdername, string expiration) {
            base.Channel.modifyClientCard(id, holdername, expiration);
        }
        
        public System.Threading.Tasks.Task modifyClientCardAsync(int id, string holdername, string expiration) {
            return base.Channel.modifyClientCardAsync(id, holdername, expiration);
        }
        
        public void deleteClientCard(int id) {
            base.Channel.deleteClientCard(id);
        }
        
        public System.Threading.Tasks.Task deleteClientCardAsync(int id) {
            return base.Channel.deleteClientCardAsync(id);
        }
        
        public void createClientCard(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration) {
            base.Channel.createClientCard(id, client_id, type, card_number, security_code, holdername, expiration);
        }
        
        public System.Threading.Tasks.Task createClientCardAsync(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration) {
            return base.Channel.createClientCardAsync(id, client_id, type, card_number, security_code, holdername, expiration);
        }
        
        public void createTemporaryClientCard(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration, string delete_on) {
            base.Channel.createTemporaryClientCard(id, client_id, type, card_number, security_code, holdername, expiration, delete_on);
        }
        
        public System.Threading.Tasks.Task createTemporaryClientCardAsync(int id, int client_id, string type, string card_number, string security_code, string holdername, string expiration, string delete_on) {
            return base.Channel.createTemporaryClientCardAsync(id, client_id, type, card_number, security_code, holdername, expiration, delete_on);
        }
        
        public void modifyDeliveryAddress(int id, string country, string province, string city, string street, int civicnumber, string appartment, string zipcode) {
            base.Channel.modifyDeliveryAddress(id, country, province, city, street, civicnumber, appartment, zipcode);
        }
        
        public System.Threading.Tasks.Task modifyDeliveryAddressAsync(int id, string country, string province, string city, string street, int civicnumber, string appartment, string zipcode) {
            return base.Channel.modifyDeliveryAddressAsync(id, country, province, city, street, civicnumber, appartment, zipcode);
        }
        
        public void createDeliveryAddress(string country, string province, string city, string street, int civicnumber, string appartment, string zipcode, int client_id) {
            base.Channel.createDeliveryAddress(country, province, city, street, civicnumber, appartment, zipcode, client_id);
        }
        
        public System.Threading.Tasks.Task createDeliveryAddressAsync(string country, string province, string city, string street, int civicnumber, string appartment, string zipcode, int client_id) {
            return base.Channel.createDeliveryAddressAsync(country, province, city, street, civicnumber, appartment, zipcode, client_id);
        }
        
        public void deleteDeliveryAddress(int id) {
            base.Channel.deleteDeliveryAddress(id);
        }
        
        public System.Threading.Tasks.Task deleteDeliveryAddressAsync(int id) {
            return base.Channel.deleteDeliveryAddressAsync(id);
        }
        
        public void getServicesList() {
            base.Channel.getServicesList();
        }
        
        public System.Threading.Tasks.Task getServicesListAsync() {
            return base.Channel.getServicesListAsync();
        }
        
        public void getServiceById(int id) {
            base.Channel.getServiceById(id);
        }
        
        public System.Threading.Tasks.Task getServiceByIdAsync(int id) {
            return base.Channel.getServiceByIdAsync(id);
        }
        
        public void getClientTransactionById(int id) {
            base.Channel.getClientTransactionById(id);
        }
        
        public System.Threading.Tasks.Task getClientTransactionByIdAsync(int id) {
            return base.Channel.getClientTransactionByIdAsync(id);
        }
        
        public void createClientTransaction(int id, int card_id, string transaction_confirmation, string status, string validation, double amount, int order_id, string date) {
            base.Channel.createClientTransaction(id, card_id, transaction_confirmation, status, validation, amount, order_id, date);
        }
        
        public System.Threading.Tasks.Task createClientTransactionAsync(int id, int card_id, string transaction_confirmation, string status, string validation, double amount, int order_id, string date) {
            return base.Channel.createClientTransactionAsync(id, card_id, transaction_confirmation, status, validation, amount, order_id, date);
        }
        
        public void getStockIns() {
            base.Channel.getStockIns();
        }
        
        public System.Threading.Tasks.Task getStockInsAsync() {
            return base.Channel.getStockInsAsync();
        }
        
        public void getStockInListByPcode(string pcode) {
            base.Channel.getStockInListByPcode(pcode);
        }
        
        public System.Threading.Tasks.Task getStockInListByPcodeAsync(string pcode) {
            return base.Channel.getStockInListByPcodeAsync(pcode);
        }
        
        public void getStockOuts() {
            base.Channel.getStockOuts();
        }
        
        public System.Threading.Tasks.Task getStockOutsAsync() {
            return base.Channel.getStockOutsAsync();
        }
    }
}
